from ʟaʄɨօ import *
import time
from Cula import *
from knite import *
from PPPADADWDKMNCAQWNOPKNQWD import *
if Kryogenesis.YOUELMX in otohi:                                
    LOGS.info("🥮________𝙱𝚘𝚘𝚝𝚒𝚗𝚐 YօʊɛʟʍӼ 𝙴𝚗𝚐𝚒𝚗𝚎________🥮")
    LOGS.info("| _ )   ___    ___   | |_    (_)   _ _    / _|")
    LOGS.info("| _ \  / _ \  / _ \  |  _|   | |  | ' \   \__|")
    LOGS.info("|___/  \___/  \___/  _\__|  _|_|_ |_||_|  |__|")
    LOGS.info("🥮________------------------------________🥮")
    LOGS.info("")
    LOGS.info("➢🥮________YօʊɛʟʍӼ engine is now going to start________🥮")
    LOGS.info("")
    LOGS.info("")
    LOGS.info("=|-  *    🔥(       (   🔥(      ) 🔥(    (      🔥) (    (   (    (") 
    time.sleep(1)
    LOGS.info("=|-  )    ) 🔥(  `   )\ 🔥)    )\🔥 ) )\ ) 🔥*   ) ( /( 🔥*   🔥*   ")
    time.sleep(1)
    LOGS.info("=|-  ( 🔥/( ( 🔥/( )\🔥))( 🔥(()/(🔥(  ((🔥)/(((🔥)/` )  🔥/( )🔥/( ")
    time.sleep(1)
    LOGS.info("=|-  )\(🔥)))\(🔥)((_)(🔥)\ /(_🔥))\ 🔥 /(_🔥))/(_)( 🔥)(_)((_🔥(_🔥")
    time.sleep(1)
    LOGS.info("=|-  (🔥(_)\🔥((_)\🔥(_()🔥((_🔥(_))🔥((_)🔥(_))🔥(_))🔥(_🔥(_🔥(_🔥")
    time.sleep(1) 
    LOGS.info("=|-📥██╗░░░██╗░█████╗░██╗░░░██╗███████╗██╗░░░░░███╗░░░███╗██╗░░██╗📥")
    time.sleep(1)
    LOGS.info("=|-📥╚██╗░██╔╝██╔══██╗██║░░░██║██╔════╝██║░░░░░████╗░████║╚██╗██╔╝📥") 
    time.sleep(1)
    LOGS.info("=|-📥░╚████╔╝░██║░░██║██║░░░██║█████╗░░██║░░░░░██╔████╔██║░╚███╔╝░📥")
    time.sleep(1)
    LOGS.info("=|-📥░░╚██╔╝░░██║░░██║██║░░░██║██╔══╝░░██║░░░░░██║╚██╔╝██║░██╔██╗░📥")
    time.sleep(1)
    LOGS.info("=|-📥░░░██║░░░╚█████╔╝╚██████╔╝███████╗███████╗██║░╚═╝░██║██╔╝╚██╗📥")
    time.sleep(1)
    LOGS.info("=|-📥░░░╚═╝░░░░╚════╝░░╚═════╝░╚══════╝╚══════╝╚═╝░░░░░╚═╝╚═╝░░╚═╝📥")
    LOGS.info("")
    LOGS.info("")
    LOGS.info("=|- |   YօʊɛʟʍӼ ♚ＲＥＡＤＹ♚  |")
    time.sleep(2) 
    LOGS.info("")  
    LOGS.info("=|- ɢᴇᴛᴛɪɴɢ ᴀʟʟ ꜰɪʟᴇꜱ ʀᴇᴀᴅʏ 📩")
    LOGS.info("")
    LOGS.info("=|- ꜱʏɴᴄɪɴɢ ᴅᴏɴᴇ 🧧")
    LOGS.info("=|  ᴍᴏᴠɪɴɢ ᴏɴ 🎏")
    time.sleep(1) 
    LOGS.info("=|- Checking ELEMENT Files 📨")
    time.sleep(3)
    LOGS.info("=|- ꜱʏɴᴄɪɴɢ ᴅᴏɴᴇ 🧧")
    LOGS.info("=|  ᴍᴏᴠɪɴɢ ᴏɴ 🎏")
    os.system("python -m ʏօʊȶʊɮɛʟɨ")
else:
    LOGS.info("")
    LOGS.info("")
    LOGS.info("")
    LOGS.info("")
    LOGS.info("=|- ᗯᖇOᑎG 𝗬𝗢𝗨𝗘𝗟𝗠𝗫_𝗞𝗘𝗬 ᴏʀ ɴᴏ 𝗬𝗢𝗨𝗘𝗟𝗠𝗫_𝗞𝗘𝗬")
    time.sleep(2)
    LOGS.info("=|- ᴘʟᴇᴀꜱᴇ ᴄʜᴇᴄᴋ ʏᴏᴜʀ 𝗬𝗢𝗨𝗘𝗟𝗠𝗫_𝗞𝗘𝗬")
    time.sleep(2)
    LOGS.info("=|- ɴᴏᴡᴀʏ YօʊɛʟʍӼ engine ᴄᴀɴ ʟᴇᴛ ʏᴏᴜ ᴄᴏɴᴛɪɴᴜᴇ!")
    time.sleep(2)
    LOGS.info("=|- ᴘᴜᴛ ᴛʜᴇ ᴄᴏʀʀᴇᴄᴛ 𝗬𝗢𝗨𝗘𝗟𝗠𝗫_𝗞𝗘𝗬 ᴀɴᴅ ʀᴇᴅᴇᴘʟᴏʏ ᴛʜᴇ ʙᴏᴛ.")
    time.sleep(2)
    LOGS.info("=|- ❗️ 𝐄𝐗𝐈𝐓𝐈𝐍𝐆 𝐀𝐍𝐃 𝐂𝐋𝐄𝐀𝐍𝐈𝐍𝐆 𝐄𝐍𝐓𝐈𝐑𝐄 𝐒𝐎𝐔𝐑𝐂𝐄-𝐂𝐎𝐃𝐄 ❗️")
    time.sleep(2)
    try:
        shutil.rmtree(K)
        shutil.rmtree(P)
        shutil.rmtree(V)
        shutil.rmtree(Y)
        shutil.rmtree(M)
    except:
        LOGS.info("𝙈𝙖𝙣𝙪𝙖𝙡 𝙀𝙧𝙖𝙨𝙚 𝙤𝙧 𝙘𝙤𝙣𝙩𝙖𝙘𝙩 @HypeVoids or @HypeVoidSoul") 
        pass
    sys.exit()
